### ISSUE TITLE
MissingPluginException when running Example Project

### ISSUE THREAD

**Issue by mortenboye** [ardera/flutter_gpiod#3]
Im trying to get the gpiod plugin to work, but am running into a (probably trivial) issue.

Running the example project I get this error:

`[ERROR:engine/src/flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getNumChips on channel plugins.flutter.io/gpiod)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      _FlutterGpiodPlatformSide.getNumChips (package:flutter_gpiod/src/gpiod.dart:98:34)
#2      FlutterGpiod.initialize (package:flutter_gpiod/src/gpiod.dart:252:45)
#3      FlutterGpiod.ensureInitialized (package:flutter_gpiod/src/gpiod.dart:269:35)
#4      _FlutterGpiodTestAppState._testFlutterGpiod (package:flutter_gpiod_example/main.dart:19:24)
#5      _FlutterGpiodTestAppState.initState (package:flutter_gpiod_example/main.dart:74:5)`

Any clues as to what I am missing?

**Comment by ardera** [comment]
This is a platform-side error (so it's caused by an "incorrect" `flutter-pi` binary). You can try this:

- Have you made sure you're using the latest commit of the flutter-pi repo to build the `flutter-pi` binary?
- You can try compiling flutter-pi with the `--always-make` flag, since `make` sometimes doesn't notice when included header files change.
- If you're using a custom build script, make sure you pass the `-DBUILD_GPIOD_PLUGIN` flag your C compiler.

If that doesn't fix your problem, I can upload a working `flutter-pi` binary on the flutter-pi repo as a workaround.

**Comment by mortenboye** [comment]
You are spot on. I missed an essential step in updating to the latest code. Make.
Closing this issue. Thank you.
